export default function TermsPage() {
  return (
    <div className="p-8 max-w-4xl mx-auto space-y-6 text-[#f8fafc] pb-20">
      <div className="p-6 rounded-2xl bg-[#0d172e] border border-[#1e2d54] space-y-2 shadow-xl">
        <h1 className="text-[22px] font-extrabold tracking-tight">Terms of Service</h1>
        <p className="text-[12px] text-[#94a3b8]">Operational terms and environmental data usage governance.</p>
      </div>

      <div className="p-6 rounded-2xl bg-[#0d172e] border border-[#1e2d54] space-y-4 text-[13px] text-[#94a3b8] leading-relaxed shadow-xl">
        <h2 className="text-[15px] font-bold text-[#f8fafc]">1. Environmental Data Usage Notice</h2>
        <p>AeroCast NCR provides air quality and meteorological forecast intelligence for research, public awareness, and environmental decision support across Greater Delhi NCR.</p>

        <h2 className="text-[15px] font-bold text-[#f8fafc]">2. Data Provenance & Source Attribution</h2>
        <p>Air quality reanalysis datasets are derived from Copernicus CAMS European Reanalysis extractions, surface meteorology from ECMWF ERA5, and active fire radiative power from NASA FIRMS satellite thermal anomalies.</p>

        <h2 className="text-[15px] font-bold text-[#f8fafc]">3. Disclaimer of Emergency Policy Binding</h2>
        <p>Automated GRAP alerts generated by the system serve as dynamic early warning indicators and recommendations. Official policy enforcement rests with the Central Pollution Control Board (CPCB) and CAQM.</p>
      </div>
    </div>
  )
}
